name: welcome
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  intl: ^0.20.2
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8
  sqflite: ^2.2.8
  path: ^1.8.0
  firebase_storage: ^12.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - android/assets/images/gmembers.jpg
    - android/assets/images/hassain.jpg
    - android/assets/images/heather.jpg
    - android/assets/images/jedza.jpg
    - android/assets/images/mark.jpg
    - android/assets/images/morewell.jpg
    